package Interfaz;


import ConeccionDataBase.Coneccion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ConeccionDataBase.Coneccion;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author PC
 */
public class Administrador extends javax.swing.JFrame {
  
  Coneccion con= new Coneccion(); 
  Connection cn= con.EstablacerConnection();
  
  public Administrador() {
    initComponents();
    mostrarDatos();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel3 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    txtid = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    txtnombre = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    txtsexo = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    txtfechanac = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    jLabel10 = new javax.swing.JLabel();
    txtfechaIncorporacion = new javax.swing.JTextField();
    txtSaldo = new javax.swing.JTextField();
    txtComision = new javax.swing.JTextField();
    txtCargo = new javax.swing.JTextField();
    txtIdJefe = new javax.swing.JTextField();
    txtCodDep = new javax.swing.JTextField();
    txtBuscar = new javax.swing.JTextField();
    btnBuscar = new javax.swing.JButton();
    jPanel4 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    tabla = new javax.swing.JTable();
    jPanel1 = new javax.swing.JPanel();
    btnEditar = new javax.swing.JButton();
    btnGuardar = new javax.swing.JButton();
    btnEliminar = new javax.swing.JButton();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel3.setBackground(new java.awt.Color(204, 255, 255));
    jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

    jLabel1.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
    jLabel1.setText("Id");

    txtid.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
    txtid.setText("...");
    txtid.setEnabled(false);
    txtid.setRequestFocusEnabled(false);
    txtid.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtidActionPerformed(evt);
      }
    });

    jLabel2.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
    jLabel2.setText("nomEmp");

    txtnombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
    txtnombre.setText("...");

    jLabel3.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
    jLabel3.setText("sexEmp");

    txtsexo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
    txtsexo.setText("...");

    jLabel4.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
    jLabel4.setText("fecNac");

    txtfechanac.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
    txtfechanac.setText("...");

    jLabel5.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
    jLabel5.setText("fecIncorporacion");

    jLabel6.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
    jLabel6.setText("cargoE");

    jLabel7.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
    jLabel7.setText("comisionE");

    jLabel8.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
    jLabel8.setText("salEmp");

    jLabel9.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
    jLabel9.setText("codDepto");

    jLabel10.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
    jLabel10.setText("jefeID");

    txtfechaIncorporacion.setText("...");

    txtSaldo.setText("...");

    txtComision.setText("...");

    txtCargo.setText("...");

    txtIdJefe.setText("...");

    txtCodDep.setText("...");

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(txtid, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
          .addComponent(txtsexo)
          .addComponent(txtnombre)
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel2)
              .addComponent(jLabel3)
              .addComponent(jLabel1)))
          .addComponent(jLabel4)
          .addComponent(txtfechanac))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel7)
          .addComponent(txtComision, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel6)
          .addComponent(jLabel8)
          .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel5)
          .addComponent(txtfechaIncorporacion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(42, 42, 42)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(6, 6, 6)
            .addComponent(jLabel10))
          .addComponent(txtIdJefe, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel9)
          .addComponent(txtCodDep, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(43, 43, 43))
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtsexo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtfechanac, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfechaIncorporacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdJefe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodDep, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel7)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtComision, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel6)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(62, Short.MAX_VALUE))
    );

    txtBuscar.setText("...");

    btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    btnBuscar.setText("Buscar");
    btnBuscar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnBuscarActionPerformed(evt);
      }
    });

    jPanel4.setBackground(new java.awt.Color(153, 153, 255));
    jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Información"));

    tabla.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null}
      },
      new String [] {
        "Id", "nomEmp", "sexEmp", "fecNac", "fecIncorporacion", "salEmp", "comisionE", "cargoE", "jefeID", "codDepto"
      }
    ));
    tabla.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tablaMouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(tabla);

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel4Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel4Layout.setVerticalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel4Layout.createSequentialGroup()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 10, Short.MAX_VALUE))
    );

    jPanel1.setBackground(new java.awt.Color(0, 153, 204));
    jPanel1.setForeground(new java.awt.Color(0, 204, 204));

    btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    btnEditar.setText("Editar");
    btnEditar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEditarActionPerformed(evt);
      }
    });

    btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    btnGuardar.setText("Gaurdar");
    btnGuardar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnGuardarActionPerformed(evt);
      }
    });

    btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    btnEliminar.setText("Eliminar");
    btnEliminar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEliminarActionPerformed(evt);
      }
    });

    jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jButton1.setText("Limpiar");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    jButton2.setText("jButton2");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(btnGuardar)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(btnEliminar)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jButton1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(15, 15, 15)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnEditar)
          .addComponent(btnEliminar)
          .addComponent(btnGuardar)
          .addComponent(jButton1)
          .addComponent(jButton2))
        .addContainerGap(67, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(180, 180, 180)
            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnBuscar))
          .addGroup(layout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(1547, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(btnBuscar)))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(26, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
    String sql = "INSERT INTO empleados (nomEmp, sexEmp, fecNac, fecIncorporacion, salEmp, comisionE, cargoE, jefeID, codDepto) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?,?)";
    
    try {
        PreparedStatement pst = cn.prepareStatement(sql);
        pst.setString(1, txtnombre.getText());
        pst.setString(2, txtsexo.getText());
        pst.setString(3, txtfechanac.getText());
        pst.setString(4, txtfechaIncorporacion.getText());
        pst.setString(5, txtSaldo.getText());
        pst.setString(6, txtComision.getText());
        pst.setString(7, txtCargo.getText());
        pst.setString(8, txtIdJefe.getText());
        pst.setString(9, txtCodDep.getText());
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "empleado ingresado al dedillo");
        
        limpiarCampos();
  }//GEN-LAST:event_btnGuardarActionPerformed
    catch (Exception ex) {
      System.out.println("error: "+ex);
    }
  }
  private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
    int selectedRow = tabla.getSelectedRow();
        try {
            String updateQuery = "UPDATE empleados SET nomEmp='" + txtnombre.getText() + "', "
                    + "sexEmp='" + txtsexo.getText() + "', fecNac='" + txtfechanac.getText() + "', "
                    + "fecIncorporacion='" + txtfechaIncorporacion.getText() + "', salEmp='" + txtSaldo.getText() + "', "
                    + "comisionE='" + txtComision.getText() + "', cargoE='" + txtCargo.getText() + "', "
                    + "jefeID='" + txtIdJefe.getText() + "', codDepto='" + txtCodDep.getText() + "' WHERE Id='" + txtid.getText() + "'";

            PreparedStatement pst = cn.prepareStatement(updateQuery);

            int result = pst.executeUpdate();

            if (result > 0) {
                JOptionPane.showMessageDialog(null, "Registro actualizado correctamente");
                mostrarDatos(); // Refresh the table
                limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo actualizar el registro");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al actualizar el registro: " + ex.getMessage());
        }
    
  }//GEN-LAST:event_btnEditarActionPerformed

  private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
    String buscar = txtBuscar.getText().trim();
    
    if (!buscar.isEmpty()) {
    } else {
        JOptionPane.showMessageDialog(null, "Ingrese un valor para buscar");
    }
  }//GEN-LAST:event_btnBuscarActionPerformed

  private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
    btnGuardar.setEnabled(false);
    btnEditar.setEnabled(true);
    btnEliminar.setEnabled(true);
    int fila = tabla.getSelectedRow();
    if (fila == -1) {
        JOptionPane.showMessageDialog(null, "Seleccione una fila");
    } else {
        // Set the selected row data to the text fields
        txtid.setText(tabla.getValueAt(fila, 0).toString());
        txtnombre.setText(tabla.getValueAt(fila, 1).toString());
        txtsexo.setText(tabla.getValueAt(fila, 2).toString());
        txtfechanac.setText(tabla.getValueAt(fila, 3).toString());
        txtfechaIncorporacion.setText(tabla.getValueAt(fila, 4).toString());
        txtSaldo.setText(tabla.getValueAt(fila, 5).toString());
        txtComision.setText(tabla.getValueAt(fila, 6).toString());
        txtCargo.setText(tabla.getValueAt(fila, 7).toString());
        txtIdJefe.setText(tabla.getValueAt(fila, 8).toString());
        txtCodDep.setText(tabla.getValueAt(fila, 9).toString());
    }
  
  }//GEN-LAST:event_tablaMouseClicked

  private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
      int selectedRow = tabla.getSelectedRow();

    if (selectedRow != -1) {
        try {
            String deleteQuery = "DELETE FROM empleados WHERE Id='" + txtid.getText() + "'";

            Statement st = cn.createStatement();
            int result = st.executeUpdate(deleteQuery);

            if (result > 0) {
                JOptionPane.showMessageDialog(null, "Registro eliminado correctamente");
                mostrarDatos(); // Refresh the table
                limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo eliminar el registro");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al eliminar el registro: " + ex.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(null, "Selecciona una fila para eliminar");
    }
  }//GEN-LAST:event_btnEliminarActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
limpiarCampos();
btnGuardar.setEnabled(true);
  }//GEN-LAST:event_jButton1ActionPerformed

  private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtidActionPerformed

  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Administrador().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnBuscar;
  private javax.swing.JButton btnEditar;
  private javax.swing.JButton btnEliminar;
  private javax.swing.JButton btnGuardar;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JScrollPane jScrollPane1;
  public javax.swing.JTable tabla;
  public javax.swing.JTextField txtBuscar;
  public javax.swing.JTextField txtCargo;
  public javax.swing.JTextField txtCodDep;
  public javax.swing.JTextField txtComision;
  public javax.swing.JTextField txtIdJefe;
  public javax.swing.JTextField txtSaldo;
  public javax.swing.JTextField txtfechaIncorporacion;
  public javax.swing.JTextField txtfechanac;
  public javax.swing.JTextField txtid;
  public javax.swing.JTextField txtnombre;
  public javax.swing.JTextField txtsexo;
  // End of variables declaration//GEN-END:variables

  private void mostrarDatos() {
    DefaultTableModel modelo= new DefaultTableModel();
     modelo.addColumn("id");
    modelo.addColumn("nomEmp");
    modelo.addColumn("sexEmp");
    modelo.addColumn("fecNac");
    modelo.addColumn("fecIncorporacion");
    modelo.addColumn("salEmp");
    modelo.addColumn("comisionE");
    modelo.addColumn("cargoE");
    modelo.addColumn("jefeID");
        modelo.addColumn("codDepto");

    
    
    tabla.setModel(modelo);
    String consul = "select * from empleados";
    String[] datos = new String[10];
    Statement st;
    try {
        st = cn.createStatement();
        ResultSet rs = st.executeQuery(consul);
        while (rs.next()) {
            datos[0] = rs.getString(1);
            datos[1] = rs.getString(2);
            datos[2] = rs.getString(3);
            datos[3] = rs.getString(4);
            datos[4] = rs.getString(5);
            datos[5] = rs.getString(6);
            datos[6] = rs.getString(7);
            datos[7] = rs.getString(8);
            datos[8] = rs.getString(9);
            datos[9] = rs.getString(10);
         
            modelo.addRow(datos);
        }
    
  }
    catch (Exception ex) {
      System.out.println(ex);
    }
}

  private void limpiarCampos() {

    txtid.setText("");
    txtnombre.setText("");
    txtsexo.setText("");
    txtfechanac.setText("");
    txtfechaIncorporacion.setText("");
    txtSaldo.setText("");
    txtComision.setText("");
    txtCargo.setText("");
    txtIdJefe.setText("");
    txtCodDep.setText("");
}

  private void buscarDatos(String buscar) {
DefaultTableModel modelo = new DefaultTableModel();
    modelo.addColumn("id");
    modelo.addColumn("nomEmp");
    modelo.addColumn("sexEmp");
    modelo.addColumn("fecNac");
    modelo.addColumn("fecIncorporacion");
    modelo.addColumn("salEmp");
    modelo.addColumn("comisionE");
    modelo.addColumn("cargoE");
    modelo.addColumn("jefeID");
    modelo.addColumn("codDepto");

    tabla.setModel(modelo);

    String consulta = "SELECT * FROM empleados WHERE Id LIKE '%" + buscar + "%' OR nomEmp LIKE '%" +  buscar + "%'";

    String[] datos = new String[10];
    Statement st;

    try {
        st = cn.createStatement();
        ResultSet rs = st.executeQuery(consulta);

        boolean encontrado = false;

        while (rs.next()) {
            encontrado = true;
            datos[0] = rs.getString(1);
            datos[1] = rs.getString(2);
            datos[2] = rs.getString(3);
            datos[3] = rs.getString(4);
            datos[4] = rs.getString(5);
            datos[5] = rs.getString(6);
            datos[6] = rs.getString(7);
            datos[7] = rs.getString(8);
            datos[8] = rs.getString(9);
            datos[9] = rs.getString(10);

            modelo.addRow(datos);
        }

        if (!encontrado) {
            JOptionPane.showMessageDialog(null, "No se encontraron resultados para la búsqueda");
        }

    } catch (Exception ex) {
        System.out.println(ex);
    }}
  
}
