/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import ConeccionDataBase.Coneccion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class AdministradorCliente extends javax.swing.JFrame {

  /**
   * Creates new form AdministradorCliente
   */Coneccion con= new Coneccion(); 
  Connection cn= con.EstablacerConnection();
  
  public AdministradorCliente() {
    initComponents();
    mostrarDatos();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel4 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    tabla2 = new javax.swing.JTable();
    jPanel1 = new javax.swing.JPanel();
    btnEditar = new javax.swing.JButton();
    btnGuardar = new javax.swing.JButton();
    jButton1 = new javax.swing.JButton();
    btnEliminar = new javax.swing.JButton();
    jPanel3 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    txtid = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    txtcedula = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jLabel10 = new javax.swing.JLabel();
    txtnombre = new javax.swing.JTextField();
    txtapellido = new javax.swing.JTextField();
    txtidplan = new javax.swing.JTextField();
    txtFechaIngreso = new javax.swing.JTextField();
    jLabel11 = new javax.swing.JLabel();
    txtFechaNacimiento = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    txtestadocuenta = new javax.swing.JTextField();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu7 = new javax.swing.JMenu();
    jMenu1 = new javax.swing.JMenu();
    jMenu4 = new javax.swing.JMenu();
    jMenu6 = new javax.swing.JMenu();
    jMenu2 = new javax.swing.JMenu();
    jMenu3 = new javax.swing.JMenu();
    jMenu5 = new javax.swing.JMenu();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel4.setBackground(new java.awt.Color(153, 153, 255));
    jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Información"));

    tabla2.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null}
      },
      new String [] {
        "Id", "cedula", "nombre", "apellido", "Id Plan", "Estado cuenta", "fechaNacimiento", "fechaIngreso"
      }
    ));
    tabla2.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tabla2MouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(tabla2);

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel4Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel4Layout.setVerticalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel4Layout.createSequentialGroup()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );

    jPanel1.setBackground(new java.awt.Color(0, 153, 204));
    jPanel1.setForeground(new java.awt.Color(0, 204, 204));

    btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    btnEditar.setText("Editar");
    btnEditar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEditarActionPerformed(evt);
      }
    });

    btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    btnGuardar.setText("Gaurdar");
    btnGuardar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnGuardarActionPerformed(evt);
      }
    });

    jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jButton1.setText("Limpiar");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    btnEliminar.setText("Eliminar");
    btnEliminar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEliminarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(42, 42, 42)
        .addComponent(btnGuardar)
        .addGap(18, 18, 18)
        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(btnEliminar)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jButton1)
        .addGap(72, 72, 72))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(15, 15, 15)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnEditar)
          .addComponent(btnGuardar)
          .addComponent(jButton1)
          .addComponent(btnEliminar))
        .addContainerGap(67, Short.MAX_VALUE))
    );

    jPanel3.setBackground(new java.awt.Color(204, 255, 255));
    jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

    jLabel1.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
    jLabel1.setText("Id");

    txtid.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
    txtid.setText("...");
    txtid.setEnabled(false);
    txtid.setRequestFocusEnabled(false);
    txtid.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtidActionPerformed(evt);
      }
    });

    jLabel2.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
    jLabel2.setText("cedula");

    txtcedula.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
    txtcedula.setText("...");

    jLabel5.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
    jLabel5.setText("nombre");

    jLabel6.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
    jLabel6.setText("fechaNacimiento");

    jLabel8.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
    jLabel8.setText("apellido");

    jLabel10.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
    jLabel10.setText("fechaIngreso");

    txtnombre.setText("...");

    txtapellido.setText("...");

    txtidplan.setText("...");

    txtFechaIngreso.setText("...");

    jLabel11.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
    jLabel11.setText("Id plan");

    txtFechaNacimiento.setText("...");

    jLabel7.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
    jLabel7.setText("Estado de la cuenta");

    txtestadocuenta.setText("...");

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addGap(88, 88, 88)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
            .addComponent(txtid)
            .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel2)
            .addComponent(jLabel1))
          .addComponent(jLabel8)
          .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel5)
          .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel7)
          .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
            .addComponent(txtestadocuenta, javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtidplan, javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(6, 6, 6)
            .addComponent(jLabel10))
          .addComponent(txtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(117, 117, 117))
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel5)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel8)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addComponent(jLabel11)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtidplan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel7)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtestadocuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel6)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel10)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(62, Short.MAX_VALUE))
    );

    jMenu7.setText("Interfaces");

    jMenu1.setText("Interfaz para clientes");
    jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jMenu1MouseClicked(evt);
      }
    });
    jMenu7.add(jMenu1);

    jMenu4.setText("Realizar pago");
    jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jMenu4MouseClicked(evt);
      }
    });
    jMenu7.add(jMenu4);

    jMenuBar1.add(jMenu7);

    jMenu6.setText("Cerrar sesión");

    jMenu2.setText("Salir");
    jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jMenu2MouseClicked(evt);
      }
    });
    jMenu6.add(jMenu2);

    jMenuBar1.add(jMenu6);
    jMenuBar1.add(jMenu3);

    jMenu5.setText("Interfaz del administrador para agregar clientes");
    jMenuBar1.add(jMenu5);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void tabla2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla2MouseClicked

    btnEditar.setEnabled(true);
    int fila = tabla2.getSelectedRow();
    if (fila == -1) {
      JOptionPane.showMessageDialog(null, "Seleccione una fila");
    } else {

      btnGuardar.setEnabled(false);
      // Set the selected row data to the text fields
      txtid.setText(tabla2.getValueAt(fila, 0).toString());
      txtcedula.setText(tabla2.getValueAt(fila, 1).toString());
      txtnombre.setText(tabla2.getValueAt(fila, 2).toString());
      txtapellido.setText(tabla2.getValueAt(fila, 3).toString());
      txtidplan.setText(tabla2.getValueAt(fila, 4).toString());
      txtestadocuenta.setText(tabla2.getValueAt(fila, 5).toString());
      txtFechaNacimiento.setText(tabla2.getValueAt(fila, 6).toString());
      txtFechaIngreso.setText(tabla2.getValueAt(fila, 7).toString());
    }
  }//GEN-LAST:event_tabla2MouseClicked

  private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
    int selectedRow = tabla2.getSelectedRow();
    try {
      String updateQuery = "UPDATE cliente SET " +
      "cedula='" + txtcedula.getText() + "', " +
      "nombre='" + txtnombre.getText() + "', " +
      "apellido='" + txtapellido.getText() + "', " +
      "idplan='" + txtidplan.getText() + "', " +
      "estadoCuenta='" + txtestadocuenta.getText() + "', " +
      "fechaNacimiento='" + txtFechaNacimiento.getText() + "', " +
      "fechaIngreso='" + txtFechaIngreso.getText() + "' " +
      "WHERE id ='" + txtid.getText() + "'";

      PreparedStatement pst = cn.prepareStatement(updateQuery);

      int result = pst.executeUpdate();

      if (result > 0) {
        JOptionPane.showMessageDialog(null, "Registro actualizado correctamente");
        mostrarDatos(); // Refresh the table
        limpiarCampos();
        btnGuardar.setEnabled(true);
      } else {
        JOptionPane.showMessageDialog(null, "No se pudo actualizar el registro");
      }

    } catch (Exception ex) {
      JOptionPane.showMessageDialog(null, "Error al actualizar el registro: " + ex.getMessage());
    }
  }//GEN-LAST:event_btnEditarActionPerformed

  private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
    String sql = "INSERT INTO cliente (cedula, nombre, apellido, idplan, estadoCuenta, fechaNacimiento, fechaIngreso) VALUES ( ?, ?, ?, ?, ?, ?, ?)";

    try {
      PreparedStatement pst = cn.prepareStatement(sql);
      pst.setString(1, txtcedula.getText());
      pst.setString(2, txtnombre.getText());
      pst.setString(3, txtapellido.getText());
      pst.setString(4, txtidplan.getText());
      pst.setString(5, txtestadocuenta.getText());
      pst.setString(6, txtFechaNacimiento.getText());
      pst.setString(7, txtFechaIngreso.getText());

      pst.executeUpdate();
      JOptionPane.showMessageDialog(null, "cliente ingresado al dedillo");

      //para que la tabla se actualice con el nuevo valor

      mostrarDatos();
      limpiarCampos();
  }//GEN-LAST:event_btnGuardarActionPerformed
   catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al actualizar el registro: " + ex.getMessage());
        }
  }
  
  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    limpiarCampos();
    btnGuardar.setEnabled(true);
  }//GEN-LAST:event_jButton1ActionPerformed

  private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtidActionPerformed

  private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
    int selectedRow = tabla2.getSelectedRow();

    if (selectedRow != -1) {
      try {
        String deleteQuery = "DELETE FROM cliente WHERE id='" + txtid.getText() + "'";

        Statement st = cn.createStatement();
        int result = st.executeUpdate(deleteQuery);

        if (result > 0) {
          JOptionPane.showMessageDialog(null, "Registro eliminado correctamente");
          mostrarDatos(); // Refresh the table
          limpiarCampos();
          btnGuardar.setEnabled(true);
        } else {
          JOptionPane.showMessageDialog(null, "No se pudo eliminar el registro");
        }

      } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Error al eliminar el registro: " + ex.getMessage());
      }
    } else {
      JOptionPane.showMessageDialog(null, "Selecciona una fila para eliminar");
    }
  }//GEN-LAST:event_btnEliminarActionPerformed

  private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
    Administrador admin = new Administrador();
    setVisible(false);
              admin.setVisible(true);
  }//GEN-LAST:event_jMenu1MouseClicked

  private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
    InicioSesion inicio= new InicioSesion();
    setVisible(false);
              inicio.setVisible(true);
  }//GEN-LAST:event_jMenu2MouseClicked

  private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
   Ipago ipg = new Ipago();
    setVisible(false);
              ipg.setVisible(true);
  }//GEN-LAST:event_jMenu4MouseClicked

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(AdministradorCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(AdministradorCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(AdministradorCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(AdministradorCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new AdministradorCliente().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnEditar;
  private javax.swing.JButton btnEliminar;
  private javax.swing.JButton btnGuardar;
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenu jMenu2;
  private javax.swing.JMenu jMenu3;
  private javax.swing.JMenu jMenu4;
  private javax.swing.JMenu jMenu5;
  private javax.swing.JMenu jMenu6;
  private javax.swing.JMenu jMenu7;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JScrollPane jScrollPane1;
  public javax.swing.JTable tabla2;
  public javax.swing.JTextField txtFechaIngreso;
  public javax.swing.JTextField txtFechaNacimiento;
  public javax.swing.JTextField txtapellido;
  public javax.swing.JTextField txtcedula;
  public javax.swing.JTextField txtestadocuenta;
  public javax.swing.JTextField txtid;
  public javax.swing.JTextField txtidplan;
  public javax.swing.JTextField txtnombre;
  // End of variables declaration//GEN-END:variables

  private void mostrarDatos() {
    DefaultTableModel modelo= new DefaultTableModel();
     modelo.addColumn("id");
    modelo.addColumn("cedula");
    modelo.addColumn("nombre");
    modelo.addColumn("apellido");
    modelo.addColumn("idplan");
    modelo.addColumn("estadoCuenta");
    modelo.addColumn("fechaNacimiento");
    modelo.addColumn("fechaIngreso");

    
    
    tabla2.setModel(modelo);
    String consul = "select * from cliente";
    String[] datos = new String[8];
    try {
        Statement st = cn.createStatement();
        ResultSet rs = st.executeQuery(consul);
        while (rs.next()) {
            datos[0] = rs.getString(1);
            datos[1] = rs.getString(2);
            datos[2] = rs.getString(3);
            datos[3] = rs.getString(4);
            datos[4] = rs.getString(5);
            datos[5] = rs.getString(6);
            datos[6] = rs.getString(7);
            datos[7] = rs.getString(8);
                  
            modelo.addRow(datos);
        }
        
    
  }
    catch (Exception ex) {
      System.out.println(ex);
    }

  }

  private void limpiarCampos() {
  txtid.setText("");
    txtcedula.setText("");
    txtnombre.setText("");
    txtapellido.setText("");
    txtidplan.setText("");
    txtestadocuenta.setText("");
    txtFechaNacimiento.setText("");
    txtFechaIngreso.setText("");

  }

}
